
CHASSIS_PATH="D:\\CSBE\\DEVICE_FS\\input\\Eco1C1G1T1\\"
CHASSIS_NAME="Eco1C1G1T1"
VERILOG_FILE="D:\\CSBE\\DEVICE_FS\\input\\verilog_files\\and.v"
WORKING_DIR="D:\\CSBE\\"

python main.py $CHASSIS_PATH $CHASSIS_NAME $VERILOG_FILE $WORKING_DIR